### ISSUE TITLE
Remove `export`

### ISSUE THREAD

**Issue by aspeddro** [nkrkv/tree-sitter-rescript#195]
Since v10.0 `export` was removed from the syntax.

[Changelog](https://github.com/rescript-lang/rescript-compiler/blob/master/CHANGELOG.md#boom-breaking-change-5)

**Comment by nkrkv** [comment]
But it is a part of ReScript history. As a general rule of thumb, Tree-sitter grammar should be more relaxed than compiler grammar and tolerate errors. If it does not over-complicate `grammar.js` or other aspects, let it be. Let’s revisit it in 5 years when everyone forgets about `export` for sure :)
