### ISSUE TITLE
try catch without highlight

### ISSUE THREAD

**Issue by aspeddro** [nkrkv/tree-sitter-rescript#37]
![image](https://user-images.githubusercontent.com/16160544/132263103-dfd15de2-573b-4f72-afcf-539c37843c87.png)

```plaintext
NVIM v0.6.0-dev+43-g02bf251bb
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

**Comment by nkrkv** [comment]
Thanks. `try`/`catch` are not supported yet, they are on TODO-list
