### ISSUE TITLE
Suport for `and`keyword : mutually recursive types

### ISSUE THREAD

**Issue by kiuKisas** [nkrkv/tree-sitter-rescript#56]
[mutually recursive types](https://rescript-lang.org/docs/manual/latest/type#mutually-recursive-types)
Currently broken: 
![20211223_23h21m07s_grim](https://user-images.githubusercontent.com/12698940/147296148-b8a9d00e-4ce9-48e8-bc3f-dd3014837cc7.png)

**Comment by nkrkv** [comment]
Yep, thank you

**Comment by nkrkv** [comment]
Fixed by #61
