### ISSUE TITLE
Add reanalyze repository to `test_wild`

### ISSUE THREAD

**Issue by WhyThat** [nkrkv/tree-sitter-rescript#68]
Hey @nkrkv,

during #67 I try to add reanalyze repository to the test, and it had several errors in it
So it could be interesting to add it to the parser

Thanks for maintained this treesitter grammar :) 

Cheers

(I don't have time to take a look at it for now, but will when I will have more time)

**Comment by nkrkv** [comment]
Yep, `reanalyze` would be nice to have among the “wild” repos. Thank you!
