### ISSUE TITLE
Multiple modules generate an error

### ISSUE THREAD

**Issue by aspeddro** [nkrkv/tree-sitter-rescript#92]
I'm editing [Playground.res](https://github.com/rescript-association/rescript-lang.org/blob/37814f58976de11d9f0309c4d1efbe21165f513d/src/Playground.res) and the parser is generating an error.

When I comment out the `Pane` module then the error disappears.

**Comment by nkrkv** [comment]
Ah, I see what you’re pointing at. Unfortunately, I can’t see the video, it says “Video can’t be played because the file is corrupt”.

Can you describe in text what tool generates an error and when? I need a way to reproduce the problem to fix it, but now the  suite passes all the tests :confused:

**Comment by aspeddro** [comment]
1. Open [`Playground.res`](https://github.com/rescript-association/rescript-lang.org/blob/37814f58976de11d9f0309c4d1efbe21165f513d/src/Playground.res) with neovim
2. Go to line 164. You'll see a error node `ERROR [163, 0] - [1547, 6]`
3. Go to line 150 and add `{` `}` around `tab.content` => `{tab.content}`

When i run `yarn tree-sitter parse Playground.res` no error is generated.

https://user-images.githubusercontent.com/16160544/172255675-74b72672-86d9-4d56-be10-ccd9c170ec27.mp4

**Comment by nkrkv** [comment]
Makes a perfect sense. Thank you!
