### ISSUE TITLE
Commit full results of `tree-sitter generate`

### ISSUE THREAD

**Issue by lambdadog** [nkrkv/tree-sitter-rescript#96]
Most tree-sitter parsers commit the generated results of `tree-sitter generate` as it means it's much easier to bring the parser in as a dependency.

**Comment by nkrkv** [comment]
Tree-sitter makes big diffs across many files on any change. It produces quite a lot of noise. So, this repo is for sources, and here’s a repo with artifacts included: https://github.com/nkrkv/nvim-treesitter-rescript Does it solve your problem?

**Comment by nkrkv** [comment]
:thinking: but it is. The second paragraph :smiley: 

Closing this for now.
